dsu_ratings_reviews.settings:
  type: config_entity
  label: 'Email'
  mapping:
    mail_subject:
      type: label
      label: 'Subject'
      translatable: true
    mail_body:
      type: text
      label: 'Body'
      translatable: true
    rating_tos:
      type: mapping
      label: 'Terms of use'
      mapping:
        value:
          type: text
          label: 'Value'
        format:
          type: string
          label: 'Text format'
field.value.dsu_fivestar:
  type: mapping
  label: 'Default value'
  mapping:
    rating:
      type: integer
      label: 'Star rating'
    target:
      type: integer
      label: 'Target ID'
